// <auto-generated />
using System;
using HRDCManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDCManagementSystem.Migrations
{
    [DbContext(typeof(HRDCContext))]
    [Migration("20240529172500_AddIsWebNotificationEnabled")]
    partial class AddIsWebNotificationEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.UserMaster", b =>
            {
                b.Property<int>("UserSysID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSysID"));

                b.Property<DateTime?>("CreateDateTime")
                    .HasColumnType("datetime2");

                b.Property<int?>("CreateUserId")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsWebNotificationEnabled")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<DateTime?>("ModifiedDateTime")
                    .HasColumnType("datetime2");

                b.Property<int?>("ModifiedUserId")
                    .HasColumnType("int");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RecStatus")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)")
                    .HasDefaultValue("active");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserSysID");

                b.ToTable("UserMaster");
            });
        }
    }
}