// <auto-generated />
using System;
using HRDCManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRDCManagementSystem.Migrations
{
    [DbContext(typeof(HRDCContext))]
    [Migration("20251008053901_AddGoogleFormTestFields")]
    partial class AddGoogleFormTestFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Attendance", b =>
                {
                    b.Property<int>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceID"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<int>("TrainingRegSysID")
                        .HasColumnType("int");

                    b.HasKey("AttendanceID")
                        .HasName("PK__Attendan__8B69263CE09F0953");

                    b.HasIndex("TrainingRegSysID");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Certificate", b =>
                {
                    b.Property<int>("CertificateSysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateSysID"));

                    b.Property<string>("CertificatePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("CreatedTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<int>("TrainingRegSysID")
                        .HasColumnType("int");

                    b.HasKey("CertificateSysID")
                        .HasName("PK__Certific__72ED270EC371F51A");

                    b.HasIndex("TrainingRegSysID");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeSysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeSysID"));

                    b.Property<string>("AlternatePhone")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Institute")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LeftDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("UserSysID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSysID")
                        .HasName("PK__Employee__2F2B8B729836B7A4");

                    b.HasIndex("UserSysID");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<int?>("TrainerRating")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingRating")
                        .HasColumnType("int");

                    b.Property<int>("TrainingRegSysID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID")
                        .HasName("PK__Feedback__6A4BEDF6DF0D6D1B");

                    b.HasIndex("QuestionID");

                    b.HasIndex("TrainingRegSysID");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.FeedbackQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.HasKey("QuestionID")
                        .HasName("PK__Feedback__0DC06F8C4E48D008");

                    b.ToTable("FeedbackQuestion", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.HelpQuery", b =>
                {
                    b.Property<int>("HelpQueryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HelpQueryID"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EmployeeSysID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("ViewedByAdmin")
                        .HasColumnType("bit");

                    b.HasKey("HelpQueryID")
                        .HasName("PK__HelpQuer__D810FCCB1A14E395");

                    b.HasIndex("EmployeeSysID");

                    b.ToTable("HelpQueries", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.TrainingProgram", b =>
                {
                    b.Property<int>("TrainingSysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingSysID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("EligibilityType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("GoogleFormTestLink")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsMarksEntry")
                        .HasColumnType("bit");

                    b.Property<int?>("MarksOutOf")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly?>("TestAvailableFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TestAvailableUntil")
                        .HasColumnType("date");

                    b.Property<string>("TestInstructions")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Validtill")
                        .HasColumnType("date");

                    b.Property<string>("Venue")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<TimeOnly>("fromTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("toTime")
                        .HasColumnType("time");

                    b.HasKey("TrainingSysID")
                        .HasName("PK__Training__2074D07C22C7D272");

                    b.ToTable("TrainingProgram", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.TrainingRegistration", b =>
                {
                    b.Property<int>("TrainingRegSysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingRegSysID"));

                    b.Property<bool>("Confirmation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeSysID")
                        .HasColumnType("int");

                    b.Property<int?>("Marks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<bool>("Registration")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TrainingSysID")
                        .HasColumnType("int");

                    b.HasKey("TrainingRegSysID")
                        .HasName("PK__Training__41BEF6152682766B");

                    b.HasIndex("EmployeeSysID");

                    b.HasIndex("TrainingSysID");

                    b.ToTable("TrainingRegistration", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.UserMaster", b =>
                {
                    b.Property<int>("UserSysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSysID"));

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserSysID")
                        .HasName("PK__UserMast__943B35EB7FC0947C");

                    b.HasIndex(new[] { "Email" }, "UQ_Email")
                        .IsUnique();

                    b.ToTable("UserMaster", (string)null);
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Attendance", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.TrainingRegistration", "TrainingRegSys")
                        .WithMany("Attendances")
                        .HasForeignKey("TrainingRegSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__RegSy__70DDC3D8");

                    b.Navigation("TrainingRegSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Certificate", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.TrainingRegistration", "RegSys")
                        .WithMany("Certificates")
                        .HasForeignKey("TrainingRegSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__RegSy__7E37BEF6");

                    b.Navigation("RegSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Employee", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.UserMaster", "UserSys")
                        .WithMany("Employees")
                        .HasForeignKey("UserSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Employee__UserSy__628FA481");

                    b.Navigation("UserSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Feedback", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.FeedbackQuestion", "Question")
                        .WithMany("Feedbacks")
                        .HasForeignKey("QuestionID")
                        .HasConstraintName("FK__Feedback__Questi__787EE5A0");

                    b.HasOne("HRDCManagementSystem.Models.Entities.TrainingRegistration", "RegSys")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TrainingRegSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__RegSys__778AC167");

                    b.Navigation("Question");

                    b.Navigation("RegSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.HelpQuery", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.Employee", "EmployeeSys")
                        .WithMany()
                        .HasForeignKey("EmployeeSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HelpQueri__Emplo__NEWCONSTRAINT");

                    b.Navigation("EmployeeSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.TrainingRegistration", b =>
                {
                    b.HasOne("HRDCManagementSystem.Models.Entities.Employee", "EmployeeSys")
                        .WithMany("TrainingRegistrations")
                        .HasForeignKey("EmployeeSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TrainingR__Emplo__6C190EBB");

                    b.HasOne("HRDCManagementSystem.Models.Entities.TrainingProgram", "TrainingSys")
                        .WithMany("TrainingRegistrations")
                        .HasForeignKey("TrainingSysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TrainingR__Train__6D0D32F4");

                    b.Navigation("EmployeeSys");

                    b.Navigation("TrainingSys");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.Employee", b =>
                {
                    b.Navigation("TrainingRegistrations");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.FeedbackQuestion", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.TrainingProgram", b =>
                {
                    b.Navigation("TrainingRegistrations");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.TrainingRegistration", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Certificates");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HRDCManagementSystem.Models.Entities.UserMaster", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
